using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using PortfolioBackend.Data;

namespace PortfolioBackend.Migrations;

[DbContext(typeof(AppDbContext))]
[Migration("20260904090000_AddEducation")]
public sealed class AddEducation : Migration
{
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql("""CREATE TABLE IF NOT EXISTS "Educations" ("Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "Degree" text NOT NULL, "Institution" text NOT NULL, "Location" text NOT NULL, "StartDate" text NOT NULL, "EndDate" text NOT NULL, "IsCurrent" boolean NOT NULL, "Description" text NOT NULL, "Grade" text NOT NULL, "Visible" boolean NOT NULL, "DisplayOrder" integer NOT NULL, "CreatedAt" timestamp with time zone NOT NULL);""");
        migrationBuilder.Sql("""ALTER TABLE "ProfileSettings" ADD COLUMN IF NOT EXISTS "EducationEnabled" boolean NOT NULL DEFAULT TRUE;""");
    }

    protected override void Down(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.DropTable("Educations");
        migrationBuilder.DropColumn("EducationEnabled", "ProfileSettings");
    }
}
